## Advanced Control for Robotics - Homework 3

####<p align="right"> 涂志鑫 12131094 </p>
####<p align="right"> 2022.03 </p>


#### Problem 1

#### Solution: 
（a)  $T_{rs}$ means the frame-{s} relative to the frame-{r}.
$$T_{rs} = T_{ar}^{-1} T_{ea}^{-1} T_{es}$$
（b） The coordinates of the frame {S} origin as seen from frame {r} is $^rS$, it can be expressed by 
$$\left[\begin{matrix} {^{r}S} \\  1 \end{matrix}\right] = T_{er}^{-1}  \left[\begin{matrix} {^{e}S} \\  1 \end{matrix}\right]  = \left[\begin{matrix} -1&0&0&1 \\  0&1&0&-1 \\0&0&-1&1 \\0&0&0&1 \end{matrix}\right] \left[\begin{matrix} 1\\1 \\1\\  1 \end{matrix}\right] = \left[\begin{matrix} 0\\0\\0 \\  1 \end{matrix}\right] $$
$$^{r}S = \left[\begin{matrix} 0\\0\\0\end{matrix}\right]$$


#### Problem 2

##### Solution:
The screw axis, $\hat{S} =(0,0,1)$ , $q =(0,0,3)$ and $h=2$.
<div align=center>
<img src=prom2.png width = 50% />
</div>



#### Problem 3

#### Solution:
The zero position configuration of end-effector M is 
$$ 
  M = \left[\begin{matrix} -1&0&0&0 \\  0&1&0&6 \\0&0&-1&2 \\0&0&0&1 \end{matrix}\right]
$$
$\hat{^sS_1} = [0,0,1]^T$, $q =[0,4,0]$
The screw axis of joint1 is $^s\hat{S_1} = \left[\begin{matrix} 0 \\  0 \\1 \\4\\0\\0 \end{matrix}\right]$.

Joint2 is pure translation, 
The screw axis of joint2 is $^s\hat{S_2} = \left[\begin{matrix} 0 \\  0 \\0\\0\\1\\0 \end{matrix}\right]$.

$\hat{^sS_3} = [0,0,-1]^T$, $q =[0,6,0]$, $h = 0.1m/rad$
$^s\pmb{v} = h\hat{S} + \pmb{w} \times (-^sq) = [-6,0,-0.1]^T$
The screw axis of joint3 is $^s\hat{S_3} = \left[\begin{matrix} 0 \\  0 \\-1 \\-6\\0\\-0.1 \end{matrix}\right]$.
Then use the func 'FKinSpace' to get the result of configuration.

In [9]:
# problem 4
import numpy as np
import modern_robotics as mr
# help(mr.FKinSpace)
M = np.array([[-1, 0,  0, 0],
                      [ 0, 1,  0, 6],
                      [ 0, 0, -1, 2],
                      [ 0, 0,  0, 1]])
Slist = np.array([[0, 0,  1,  4, 0,    0],
                          [0, 0,  0,  0, 1,    0],
                          [0, 0, -1, -6, 0, -0.1]]).T
thetalist = np.array([np.pi / 2.0, 3, np.pi])
T = mr.FKinSpace(M,Slist,thetalist)
print('The end-effector configuration is:\n',T)

The end-effector configuration is:
 [[-1.14423775e-17  1.00000000e+00  0.00000000e+00 -5.00000000e+00]
 [ 1.00000000e+00  1.14423775e-17  0.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  1.68584073e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]



#### Problem 4

#### Solution
(a)
<div align=center>
<img src=prom4.jpg width = 40% />
</div>

Assume the center of the circle plate is O, $^O\nu_b = [0,0,1,0,0,0]^T$
$^b\pmb{v_b} =\pmb{w}\times \pmb{^bOb} = [0,0,1]^T\times [10,0,0]^T $.
 $$^b\nu_b = [0,0,1,0,10,0]^T$$

(b) The initial transformation matrix of b in {s}, 
            $$M = \left[\begin{matrix}  1&0&0&10 \\  0&1&0&0 \\0&0&1&-20 \\0&0&0&1 \end{matrix}\right]$$
$^s \bar{s_1} = [0,1,0,0,0,0]^T$, $^s\bar{s_2} = [0,0,1,0,0,0]^T$

$$\begin{aligned} 
^sT_b &= e^{[^s\bar{s_1}]\theta} e^{[^s\bar{s_2}]\theta} M \\
    &=e^{ \left[\begin{matrix}  0&0&t&0 \\  0&0&0&0 \\-t&0&0&0 \\0&0&0&0 \end{matrix}\right]}e^{\left[\begin{matrix}   0&-t&0&0 \\  t&0&0&0 \\0&0&0&0 \\0&0&0&0 \end{matrix}\right]}\left[\begin{matrix}  1&0&0&10 \\  0&1&0&0 \\0&0&1&-20 \\0&0&0&1 \end{matrix}\right]\\
    &= \left(\begin{array}{cccc} \cos\left(t\right) & 0 & \sin\left(t\right) & 10\,\cos\left(t\right)-20\,\sin\left(t\right)\\ 0 & 1 & 0 & 0\\ -\sin\left(t\right) & 0 & \cos\left(t\right) & -20\,\cos\left(t\right)-10\,\sin\left(t\right)\\ 0 & 0 & 0 & 1 \end{array}\right)
\end{aligned} $$

$$p(t) = \left(\begin{array}{c} 10\,\cos\left(t\right)-20\,\sin\left(t\right)\\ 0\\ -20\,\cos\left(t\right)-10\,\sin\left(t\right) \end{array}\right)$$

The linear velocity  $\dot p(t) = \left(\begin{array}{c} -20\,\cos\left(t\right)-10\,\sin\left(t\right)\\ 0\\ -10\,\cos\left(t\right)+20\,\sin\left(t\right) \end{array}\right)$


#### Problem 5

#### Solution:
(a)
The initial transformation matrix of b in {s}, 
            $$M = \left[\begin{matrix}  -1&0&0&0 \\  0&0&1&3 \\0&1&0&-2 \\0&0&0&1 \end{matrix}\right]$$
$^s \bar{s_1} = [0,1,0,0,0,0]^T$, $^s\bar{s_2} = [1,0,0,0,-2,0]^T$, $^s\bar{s_2} = [0,0,0,0,1,0]^T$
When the $\theta = (90^{\circ},90^{\circ},1)$, use the func 'FKinSpace' to get the result of configuration.


In [2]:
# problem 5
import numpy as np
import modern_robotics as mr
# help(mr.FKinSpace)

# show the forward kinematics configuration.
M = np.array([[-1, 0,  0, 0],   
              [ 0, 0,  1, 3],
              [ 0, 1, 0, -2],
              [ 0, 0,  0, 1]])
Slist = np.array([[0, 1,  0,  0, 0,    0],
                          [1, 0,  0,  0, -2, 0],
                          [0, 0, 0, 0, 1, 0]]).T
thetalist = np.array([np.pi / 2.0, np.pi / 2.0, 1])
T = mr.FKinSpace(M,Slist,thetalist)
print('The end-effector configuration is:\n',T)

# draw the arm and the end-effector frame in this configuration


# obtain the sapce jacobian
Js = mr.JacobianSpace(Slist,thetalist)
print('The sapce jacobian for this configuration is:\n',Js)

The end-effector configuration is:
 [[-1.11022302e-16  1.11022302e-16  1.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  1.11022302e-16  4.44089210e-16]
 [ 1.00000000e+00  1.23259516e-32  1.11022302e-16  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
The sapce jacobian for this configuration is:
 [[ 0.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.11022302e-16]]


#### Problem 6
Consider the robot shown in Fig.4.3.
 
(a) Use Drake to build this robot model (similar to the example we discussed during class) and show the snapshots of the Meshcat visualization at three different sets of joint positions.

(b) Write your own forward kinematics function (using PoE) to compute the pose of the end-effector frame (i.e. frame {3}) relative to the world frame {0}. Test your function for a few different sets of joint positions and compare your results with Drake’s built-in function.

(c) Write your own function to compute the geometric Jacobian of the end-effector frame (i.e. frame {3}) expressed in the world frame {0}. Test your function for a few different sets of joint positions and compare your results with Drake’s built-in function.

(d) Let q be a point attached to frame {3} with local coordinate $^3q = (1, 2, 3)$.

1.Derive the (analytic) Jacobian 0Ja(θ), i.e., $^0\dot{q} = ^0J_a(θ)\dot{θ}$. Show all your steps.

2.Write a function in Drake to implement your formula. Test your function for a few
different sets of joint positions/joint velocities, and compare your results with the Drake’s built-in function.

#### Solution:

 




In [11]:
# problem 6
import numpy as np