## Advanced Control for Robotics - Homework 3

####<p align="right"> 涂志鑫 12131094 </p>
####<p align="right"> 2022.03 </p>


#### Problem 1

#### Solution: 
（a)  $T_{rs}$ means the frame-{s} relative to the frame-{r}.
$$T_{rs} = T_{ar}^{-1} T_{ea}^{-1} T_{es}$$
（b） The coordinates of the frame {S} origin as seen from frame {r} is $^rS$, it can be expressed by 
$$\left[\begin{matrix} {^{r}S} \\  1 \end{matrix}\right] = T_{er}^{-1}  \left[\begin{matrix} {^{e}S} \\  1 \end{matrix}\right]  = \left[\begin{matrix} -1&0&0&1 \\  0&1&0&-1 \\0&0&-1&1 \\0&0&0&1 \end{matrix}\right] \left[\begin{matrix} 1\\1 \\1\\  1 \end{matrix}\right] = \left[\begin{matrix} 0\\0\\0 \\  1 \end{matrix}\right] $$
$$^{r}S = \left[\begin{matrix} 0\\0\\0\end{matrix}\right]$$


#### Problem 2

##### Solution:
The screw axis, $\hat{S} =(0,0,1)$ , $q =(0,0,3)$ and $h=2$.
<div align=center>
<img src=prom2.png width = 50% />
</div>



#### Problem 3

#### Solution:
The zero position configuration of end-effector M is 
$$ 
  M = \left[\begin{matrix} -1&0&0&0 \\  0&1&0&6 \\0&0&-1&2 \\0&0&0&1 \end{matrix}\right]
$$
$\hat{^sS_1} = [0,0,1]^T$, $q =[0,4,0]$
The screw axis of joint1 is $^s\hat{S_1} = \left[\begin{matrix} 0 \\  0 \\1 \\4\\0\\0 \end{matrix}\right]$.

Joint2 is pure translation, 
The screw axis of joint2 is $^s\hat{S_2} = \left[\begin{matrix} 0 \\  0 \\0\\0\\1\\0 \end{matrix}\right]$.

$\hat{^sS_3} = [0,0,-1]^T$, $q =[0,6,0]$, $h = 0.1m/rad$
$^s\pmb{v} = h\hat{S} + \pmb{w} \times (-^sq) = [-6,0,-0.1]^T$
The screw axis of joint3 is $^s\hat{S_3} = \left[\begin{matrix} 0 \\  0 \\-1 \\-6\\0\\-0.1 \end{matrix}\right]$.
Then use the func 'FKinSpace' to get the result of configuration.

In [9]:
# problem 4
import numpy as np
import modern_robotics as mr
# help(mr.FKinSpace)
M = np.array([[-1, 0,  0, 0],
                      [ 0, 1,  0, 6],
                      [ 0, 0, -1, 2],
                      [ 0, 0,  0, 1]])
Slist = np.array([[0, 0,  1,  4, 0,    0],
                          [0, 0,  0,  0, 1,    0],
                          [0, 0, -1, -6, 0, -0.1]]).T
thetalist = np.array([np.pi / 2.0, 3, np.pi])
T = mr.FKinSpace(M,Slist,thetalist)
print('The end-effector configuration is:\n',T)

The end-effector configuration is:
 [[-1.14423775e-17  1.00000000e+00  0.00000000e+00 -5.00000000e+00]
 [ 1.00000000e+00  1.14423775e-17  0.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  1.68584073e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]



#### Problem 4

#### Solution
(a)
<div align=center>
<img src=prom4.jpg width = 40% />
</div>

Assume the center of the circle plate is O, $^O\nu_b = [0,0,1,0,0,0]^T$
$^b\pmb{v_b} =\pmb{v_o}+\pmb{w}\times \pmb{^bOb} =[0,1,0]^T\times [0,0,-20]^T+ [0,0,1]^T\times [10,0,0]^T $.

 $$^b\nu_b = [0,0,1,-20,10,0]^T$$

(b) The initial transformation matrix of b in {s}, 
            $$M = \left[\begin{matrix}  1&0&0&10 \\  0&1&0&0 \\0&0&1&-20 \\0&0&0&1 \end{matrix}\right]$$
$^s \bar{s_1} = [0,1,0,0,0,0]^T$, $^s\bar{s_2} = [0,0,1,0,0,0]^T$

$$\begin{aligned} 
^sT_b &= e^{[^s\bar{s_1}]\theta} e^{[^s\bar{s_2}]\theta} M \\
    &=e^{ \left[\begin{matrix}  0&0&t&0 \\  0&0&0&0 \\-t&0&0&0 \\0&0&0&0 \end{matrix}\right]}e^{\left[\begin{matrix}   0&-t&0&0 \\  t&0&0&0 \\0&0&0&0 \\0&0&0&0 \end{matrix}\right]}\left[\begin{matrix}  1&0&0&10 \\  0&1&0&0 \\0&0&1&-20 \\0&0&0&1 \end{matrix}\right]\\
    &= \left(\begin{array}{cccc} \cos\left(t\right) & 0 & \sin\left(t\right) & 10\,\cos\left(t\right)-20\,\sin\left(t\right)\\ 0 & 1 & 0 & 0\\ -\sin\left(t\right) & 0 & \cos\left(t\right) & -20\,\cos\left(t\right)-10\,\sin\left(t\right)\\ 0 & 0 & 0 & 1 \end{array}\right)
\end{aligned} $$

$$p(t) = \left(\begin{array}{c} 10\,\cos\left(t\right)-20\,\sin\left(t\right)\\ 0\\ -20\,\cos\left(t\right)-10\,\sin\left(t\right) \end{array}\right)$$

The linear velocity  $\dot p(t) = \left(\begin{array}{c} -20\,\cos\left(t\right)-10\,\sin\left(t\right)\\ 0\\ -10\,\cos\left(t\right)+20\,\sin\left(t\right) \end{array}\right)$


#### Problem 5

#### Solution:
(a)
The initial transformation matrix of b in {s}, 
            $$M = \left[\begin{matrix}  -1&0&0&0 \\  0&0&1&3 \\0&1&0&-2 \\0&0&0&1 \end{matrix}\right]$$
$^s \bar{s_1} = [0,1,0,0,0,0]^T$, $^s\bar{s_2} = [1,0,0,0,-2,0]^T$, $^s\bar{s_2} = [0,0,0,0,1,0]^T$
When the $\theta = (90^{\circ},90^{\circ},1)$, use the func 'FKinSpace' to get the result of configuration.



In [2]:
# problem 5
import numpy as np
import modern_robotics as mr
# help(mr.FKinSpace)

# show the forward kinematics configuration.
M = np.array([[-1, 0,  0, 0],   
              [ 0, 0,  1, 3],
              [ 0, 1, 0, -2],
              [ 0, 0,  0, 1]])
Slist = np.array([[0, 1,  0,  0, 0,    0],
                          [1, 0,  0,  0, -2, 0],
                          [0, 0, 0, 0, 1, 0]]).T
thetalist = np.array([np.pi / 2.0, np.pi / 2.0, 1])
T = mr.FKinSpace(M,Slist,thetalist)
print('The end-effector configuration is:\n',T)

# draw the arm and the end-effector frame in this configuration


# obtain the sapce jacobian
Js = mr.JacobianSpace(Slist,thetalist)
print('The sapce jacobian for this configuration is:\n',Js)

The end-effector configuration is:
 [[-1.11022302e-16  1.11022302e-16  1.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  1.11022302e-16  4.44089210e-16]
 [ 1.00000000e+00  1.23259516e-32  1.11022302e-16  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
The sapce jacobian for this configuration is:
 [[ 0.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.11022302e-16]]


#### Problem 6
Consider the robot shown in Fig.4.3.
 
(a) Use Drake to build this robot model (similar to the example we discussed during class) and show the snapshots of the Meshcat visualization at three different sets of joint positions.

(b) Write your own forward kinematics function (using PoE) to compute the pose of the end-effector frame (i.e. frame {3}) relative to the world frame {0}. Test your function for a few different sets of joint positions and compare your results with Drake’s built-in function.

(c) Write your own function to compute the geometric Jacobian of the end-effector frame (i.e. frame {3}) expressed in the world frame {0}. Test your function for a few different sets of joint positions and compare your results with Drake’s built-in function.

(d) Let q be a point attached to frame {3} with local coordinate $^3q = (1, 2, 3)$.

1.Derive the (analytic) Jacobian 0Ja(θ), i.e., $^0\dot{q} = ^0J_a(θ)\dot{θ}$. Show all your steps.

2.Write a function in Drake to implement your formula. Test your function for a few
different sets of joint positions/joint velocities, and compare your results with the Drake’s built-in function.

#### Solution:

The code is shown below.

In [11]:
# problem 6
import numpy as np
import pydot
from IPython.display import display, SVG, clear_output


from pydrake.math import RigidTransform, RollPitchYaw
from pydrake.multibody.plant import AddMultibodyPlantSceneGraph
from pydrake.all import (Parser, Meshcat, DiagramBuilder,
                        MeshcatVisualizerCpp, JacobianWrtVariable,
                        MakeRenderEngineVtk, RenderEngineVtkParams)
from pydrake.geometry import (Box, Cylinder)
from pydrake.multibody.tree import (PrismaticJoint, UnitInertia, SpatialInertia, RevoluteJoint, FixedOffsetFrame, WeldJoint)
from manipulation.meshcat_cpp_utils import MeshcatJointSliders
from manipulation.scenarios import AddMultibodyTriad
meshcat = Meshcat()

[2022-04-02 17:37:59.890] [console] [info] Meshcat listening for connections at http://localhost:7001


In [22]:
# Build robot model in Drake
builder = DiagramBuilder()
plant, scene_graph = AddMultibodyPlantSceneGraph(builder, 0.0)

# parameters given by self
L0 = 0.8     #lenght of link 0
L1 = 1
L2 = 0.5
L3 = 0.5    # end effector

RGBA_Color0 = [0.5, 0.5, 0.5, 0.4]
RGBA_Color1 = [0, 0.5, 0.5, 0.4]
RGBA_Color2 = [0.6, 0, 0, 0.4]

my_model = plant.AddModelInstance("my_robot")

#SpatialInertia(mass, reference point (wrt CoM), UnitInertia()): 6x6 matrix
default_inertia = SpatialInertia(1, [0, 0, L0/2], UnitInertia(1, 1, 1))  #This does not matter for kinematics

link_0 = plant.AddRigidBody("link_0", my_model, default_inertia)

link_1 = plant.AddRigidBody("link_1", my_model, default_inertia)

link_2 = plant.AddRigidBody("link_2", my_model, default_inertia)

link_3 = plant.AddRigidBody("link_3", my_model, default_inertia)

# plant.RegisterVisualGeometry(body, 
c =0.05
plant.RegisterVisualGeometry(
    link_0,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L0/2]),
    Cylinder(c, L0),
    "link_0",
    RGBA_Color0)

plant.RegisterVisualGeometry(
    link_1,
    RigidTransform(RollPitchYaw(0, 0, 0), [L1/2, 0, 0]),
    Box(L1,c,c),
    "link_1",
    RGBA_Color1)

plant.RegisterVisualGeometry(
    link_2,
    RigidTransform(RollPitchYaw(0, 0, 0), [L2/2, 0, 0]),
    Box(L2, c, c),
    "link_2",
    RGBA_Color2)
plant.RegisterVisualGeometry(
    link_3,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L3/2]),
    Box(c, c, L3),
    "link_3",
    RGBA_Color0)

Zero_Frame = plant.AddFrame(FixedOffsetFrame('WorldFrame',
    link_0,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L0])))


Joint1_Frame = plant.AddFrame(FixedOffsetFrame(
    link_0,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L0])))

Joint2_Frame = plant.AddFrame(FixedOffsetFrame(
    link_1,
    RigidTransform(RollPitchYaw(0, np.pi/2, -np.pi/2), [L1, 0, 0])))    #rotate about fixed frame

Joint3_Frame = plant.AddFrame(FixedOffsetFrame(
    link_2,
    RigidTransform(RollPitchYaw(-np.pi/2, 0, 0), [L2, 0, 0])))

Joint1 = plant.AddJoint(RevoluteJoint(
    name="Joint1", frame_on_parent=Joint1_Frame,
    frame_on_child=link_1.body_frame(), axis=[0, 0, 1],    #axis is the ratation axis
    pos_lower_limit=-3.14,
    pos_upper_limit=3.14,
    damping=0.0))

Joint2 = plant.AddJoint(RevoluteJoint(
    name="Joint2", frame_on_parent=Joint2_Frame,
    frame_on_child=link_2.body_frame(), axis=[0, 0, 1],
    pos_lower_limit=-3.14,
    pos_upper_limit=3.14,
    damping=0.0))

Joint3 = plant.AddJoint(RevoluteJoint(
    name="Joint3", frame_on_parent=Joint3_Frame,
    frame_on_child=link_3.body_frame(), axis=[0, 0, 1],
    pos_lower_limit=-3.14,
    pos_upper_limit=3.14,
    damping=0.0))

plant.WeldFrames(
    frame_on_parent_P=plant.world_frame(),
    frame_on_child_C=link_0.body_frame(),
    X_PC=RigidTransform.Identity())


# add frames of interest
G = plant.AddFrame(FixedOffsetFrame('EndEffector',
    link_3,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L3])))


# Draw RGB frames for visualization
# only one frame for each link
for body_name in ["WorldFrame", "link_1", "link_2", "EndEffector"]:
    AddMultibodyTriad(plant.GetFrameByName(body_name), scene_graph, 0.20, 0.008)
    
    


In [23]:
# Finalize and visualize
plant.Finalize()
renderer_name = "renderer"
scene_graph.AddRenderer(renderer_name, MakeRenderEngineVtk(RenderEngineVtkParams()))
meshcat.Delete()
meshcat_vis = MeshcatVisualizerCpp.AddToBuilder(builder, scene_graph, meshcat)
diagram = builder.Build()
diagram_context = diagram.CreateDefaultContext()
diagram.Publish(diagram_context)

In [33]:
# (1) get 3 set of different joint positions

# Get world frame
theta1=0
theta2=0
theta3 = 0
plant.SetPositions(plant.GetMyContextFromRoot(diagram_context), my_model, [theta1, theta2,theta3]) # theta1, theta2
diagram.Publish(diagram_context)
plant.SetPositions(plant.GetMyContextFromRoot(diagram_context), my_model, [theta1, theta2,theta3]) # theta1, theta2
diagram.Publish(diagram_context)


plant_context = plant.GetMyMutableContextFromRoot(diagram_context)
X_W3=Joint3_Frame.CalcPoseInWorld(plant_context)
print('The pose of frame{3} of the first set of joint positions is :\n',X_W3.GetAsMatrix4())
print('----------------------------')

#the 2nd set of position
theta1=np.pi/5
theta2=np.pi/4
theta3 = np.pi/3
plant.SetPositions(plant.GetMyContextFromRoot(diagram_context), my_model, [theta1, theta2,theta3]) # theta1, theta2
diagram.Publish(diagram_context)
plant.SetPositions(plant.GetMyContextFromRoot(diagram_context), my_model, [theta1, theta2,theta3]) # theta1, theta2
diagram.Publish(diagram_context)


plant_context = plant.GetMyMutableContextFromRoot(diagram_context)
X_W3=Joint3_Frame.CalcPoseInWorld(plant_context)
print('The pose of frame{3} of the second set of joint positions is :\n',X_W3.GetAsMatrix4())
print('----------------------------')

# the 3rd set of position
theta1=np.pi/4
theta2=np.pi/6
theta3 = np.pi/3
plant.SetPositions(plant.GetMyContextFromRoot(diagram_context), my_model, [theta1, theta2,theta3]) # theta1, theta2
diagram.Publish(diagram_context)


plant_context = plant.GetMyMutableContextFromRoot(diagram_context)
X_W3=Joint3_Frame.CalcPoseInWorld(plant_context)
print('The pose of frame{3} of the third set of joint positions is :\n',X_W3.GetAsMatrix4())
print('----------------------------')


The pose of frame{3} of the first set of joint positions is :
 [[ 3.74939946e-33  0.00000000e+00  1.00000000e+00  1.00000000e+00]
 [-6.12323400e-17  1.00000000e+00  0.00000000e+00 -3.06161700e-17]
 [-1.00000000e+00 -6.12323400e-17  3.74939946e-33  3.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
----------------------------
The pose of frame{3} of the second set of joint positions is :
 [[ 5.72061403e-01 -5.87785252e-01  5.72061403e-01  1.09504770e+00]
 [ 4.15626938e-01  8.09016994e-01  4.15626938e-01  7.95598721e-01]
 [-7.07106781e-01 -1.79345371e-17  7.07106781e-01  4.46446609e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
----------------------------
The pose of frame{3} of the third set of joint positions is :
 [[ 3.53553391e-01 -7.07106781e-01  6.12372436e-01  8.83883476e-01]
 [ 3.53553391e-01  7.07106781e-01  6.12372436e-01  8.83883476e-01]
 [-8.66025404e-01 -3.06161700e-17  5.00000000e-01  3.66987298e-01]
 [ 0.00000000

(1)



In [ ]:
# write down the screw axis
import modern_robotics as mr

# step 0: compute M 
M = mr.RpToTrans(np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]]), np.array([L1, 0, -L2]))
# step 1: compute all the screw axis

Sbar_3_0=mr.ScrewToAxis(np.array([0,0,-L2]),np.array([1,0,0]),0)
Sbar_2_0=mr.ScrewToAxis(np.array([L1,0,0]),np.array([0,-1,0]),0)
Sbar_1_0=mr.ScrewToAxis(np.array([0,0,0]),np.array([0,0,1]),0)

def myPoE(theta1,theta2,theta3):
    SbarMatrix_3_0=mr.VecTose3(Sbar_3_0)
    SbarMatrix_2_0=mr.VecTose3(Sbar_2_0)
    SbarMatrix_1_0=mr.VecTose3(Sbar_1_0)
    return mr.MatrixExp6(SbarMatrix_1_0*theta1)@mr.MatrixExp6(SbarMatrix_2_0*theta2)@mr.MatrixExp6(SbarMatrix_3_0*theta3)@M


In [ ]:
Tbs = myPoE(theta1,theta2,theta3)
print(Tbs)

(2):

In [ ]:
def myGeometrixJacobian(theta1,theta2,theta3):
    SbarMatrix_2_0=mr.VecTose3(Sbar_2_0)
    SbarMatrix_1_0=mr.VecTose3(Sbar_1_0)
    # compute the SE3 for each frame
    T_01 = mr.MatrixExp6(SbarMatrix_1_0*theta1)
    T_12 = mr.MatrixExp6(SbarMatrix_2_0*theta2)
    J1 = Sbar_1_0.reshape(6,1)
    J2 = np.matmul(mr.Adjoint(T_01), Sbar_2_0.reshape(6,1))
    J3 = np.matmul(mr.Adjoint(T_01@T_12), Sbar_3_0.reshape(6,1))
    return  np.block([J1, J2, J3])

In [ ]:
J = myGeometrixJacobian(theta1,theta2,theta3)
print(J)

In [ ]:
J_G  = plant.CalcJacobianSpatialVelocity(plant_context, JacobianWrtVariable.kQDot, G, [0,0,0], Zero_Frame, Zero_Frame)
# JA_G = plant.CalcJacobianTranslationalVelocity(plant_context, JacobianWrtVariable.kQDot, G, [0,0,0], Zero_Frame, Zero_Frame)
print(J_G)
# print(JA_G)