In [1]:
import numpy as np
from pydrake.math import RigidTransform, RollPitchYaw
from pydrake.multibody.plant import AddMultibodyPlantSceneGraph
from pydrake.all import (Meshcat, DiagramBuilder,
                        MeshcatVisualizerCpp, JacobianWrtVariable,
                        MakeRenderEngineVtk, RenderEngineVtkParams)
from pydrake.geometry import (Box, Cylinder)
from pydrake.multibody.tree import (UnitInertia, SpatialInertia, RevoluteJoint, FixedOffsetFrame)
from manipulation.scenarios import AddMultibodyTriad
meshcat = Meshcat()

[2022-04-02 22:30:19.399] [console] [info] Meshcat listening for connections at http://localhost:7000


In [2]:
# Build robot model in Drake
builder = DiagramBuilder()
plant, scene_graph = AddMultibodyPlantSceneGraph(builder, 0.0)

# parameters
L0 = 0.8 #lenght of link 0
L1 = 1
L2 = 0.5
L3 = 0.08 # end effector

RGBA_Color0 = [0.5, 0.5, 0.5, 0.4]
RGBA_Color1 = [0, 0.5, 0.5, 0.4]
RGBA_Color2 = [0.9, 0, 0, 0.4]

my_model_instance = plant.AddModelInstance("my_robot")

#SpatialInertia(mass, reference point (wrt CoM), UnitInertia()): 6x6 matrix
default_inertia = SpatialInertia(1, [0, 0, L0/2], UnitInertia(1, 1, 1))  #This does not matter for kinematics

link_0 = plant.AddRigidBody("link_0", my_model_instance, default_inertia)

link_1 = plant.AddRigidBody("link_1", my_model_instance, default_inertia)

link_2 = plant.AddRigidBody("link_2", my_model_instance, default_inertia)

link_3 = plant.AddRigidBody("link_3", my_model_instance, default_inertia)

# plant.RegisterVisualGeometry(body, 
c =0.05
plant.RegisterVisualGeometry(
    link_0,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L0/2]),
    Cylinder(c, L0),
    "link_0",
    RGBA_Color0)

plant.RegisterVisualGeometry(
    link_1,
    RigidTransform(RollPitchYaw(0, 0, 0), [L1/2, 0, 0]),
    Box(L1,c,c),
    "link_1",
    RGBA_Color1)

plant.RegisterVisualGeometry(
    link_2,
    RigidTransform(RollPitchYaw(0, 0, 0), [L2/2, 0, 0]),
    Box(L2, c, c),
    "link_2",
    RGBA_Color2)
plant.RegisterVisualGeometry(
    link_3,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, 0]),
    Box(L3, L3, L3),
    "link_3",
    RGBA_Color0)

Zero_Frame = plant.AddFrame(FixedOffsetFrame('ZeroFrame',
    link_0,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L0])))


Joint1_Frame = plant.AddFrame(FixedOffsetFrame(
    link_0,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, L0])))

Joint2_Frame = plant.AddFrame(FixedOffsetFrame(
    link_1,
    RigidTransform(RollPitchYaw(0, np.pi/2, -np.pi/2), [L1, 0, 0])))

Joint3_Frame = plant.AddFrame(FixedOffsetFrame(
    link_2,
    RigidTransform(RollPitchYaw(-np.pi/2, 0, 0), [L2, 0, 0])))

Joint1 = plant.AddJoint(RevoluteJoint(
    name="Joint1", frame_on_parent=Joint1_Frame,
    frame_on_child=link_1.body_frame(), axis=[0, 0, 1],
    pos_lower_limit=-3.14,
    pos_upper_limit=3.14,
    damping=0.0))
Joint2 = plant.AddJoint(RevoluteJoint(
    name="Joint2", frame_on_parent=Joint2_Frame,
    frame_on_child=link_2.body_frame(), axis=[0, 0, 1],
    pos_lower_limit=-3.14,
    pos_upper_limit=3.14,
    damping=0.0))
Joint3 = plant.AddJoint(RevoluteJoint(
    name="Joint3", frame_on_parent=Joint3_Frame,
    frame_on_child=link_3.body_frame(), axis=[0, 0, 1],
    pos_lower_limit=-3.14,
    pos_upper_limit=3.14,
    damping=0.0))

plant.WeldFrames(
    frame_on_parent_P=plant.world_frame(),
    frame_on_child_C=link_0.body_frame(),
    X_PC=RigidTransform.Identity())

# add frames of interest
G = plant.AddFrame(FixedOffsetFrame('EndEffector',
    link_3,
    RigidTransform(RollPitchYaw(0, 0, 0), [0, 0, 0])))


In [3]:
# Draw RGB frames for visualization
# only one frame for each link
for body_name in ["ZeroFrame", "link_1", "link_2", "EndEffector"]:
    AddMultibodyTriad(plant.GetFrameByName(body_name), scene_graph, 0.20, 0.008)

In [4]:
# Finalize and visualize
plant.Finalize()
renderer_name = "renderer"
scene_graph.AddRenderer(renderer_name, MakeRenderEngineVtk(RenderEngineVtkParams()))
meshcat.Delete()
meshcat_vis = MeshcatVisualizerCpp.AddToBuilder(builder, scene_graph, meshcat)
diagram = builder.Build()
diagram_context = diagram.CreateDefaultContext()
diagram.Publish(diagram_context)

In [5]:
# write down the screw axis
import modern_robotics as mr

# step 0: compute M 
M = mr.RpToTrans(np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]]), np.array([L1, 0, -L2]))
# step 1: compute all the screw axis

Sbar_3_0=mr.ScrewToAxis(np.array([0,0,-L2]),np.array([1,0,0]),0)
Sbar_2_0=mr.ScrewToAxis(np.array([L1,0,0]),np.array([0,-1,0]),0)
Sbar_1_0=mr.ScrewToAxis(np.array([0,0,0]),np.array([0,0,1]),0)

def myPoE(M, theta1,theta2,theta3):
    SbarMatrix_3_0=mr.VecTose3(Sbar_3_0)
    SbarMatrix_2_0=mr.VecTose3(Sbar_2_0)
    SbarMatrix_1_0=mr.VecTose3(Sbar_1_0)
    return mr.MatrixExp6(SbarMatrix_1_0*theta1)@mr.MatrixExp6(SbarMatrix_2_0*theta2)@mr.MatrixExp6(SbarMatrix_3_0*theta3)@M


In [6]:
# M: The homogeneous transformation matrix at home position
theta1=np.pi/6
theta2=0
theta3=np.pi/4
plant.SetPositions(plant.GetMyContextFromRoot(diagram_context), my_model_instance, [theta1, theta2, theta3]) # theta1, theta2
diagram.Publish(diagram_context)

plant_context = plant.GetMyMutableContextFromRoot(diagram_context)
T0e = G.CalcPose(plant_context, Zero_Frame)
print(T0e.GetAsMatrix4())

[[-3.53553391e-01 -3.53553391e-01  8.66025404e-01  8.66025404e-01]
 [ 6.12372436e-01  6.12372436e-01  5.00000000e-01  5.00000000e-01]
 [-7.07106781e-01  7.07106781e-01  3.74939946e-33 -5.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [7]:
Tbs = myPoE(M, theta1,theta2,theta3)
print(Tbs)

[[-0.35355339 -0.35355339  0.8660254   0.8660254 ]
 [ 0.61237244  0.61237244  0.5         0.5       ]
 [-0.70710678  0.70710678  0.         -0.5       ]
 [ 0.          0.          0.          1.        ]]


In [8]:
def myGeometrixJacobian(theta1,theta2,theta3):
    # compute the SE3 for each frame
    SbarMatrix_2_0=mr.VecTose3(Sbar_2_0)
    SbarMatrix_1_0=mr.VecTose3(Sbar_1_0)
    # T^hat
    T_01 = mr.MatrixExp6(SbarMatrix_1_0*theta1)
    T_12 = mr.MatrixExp6(SbarMatrix_2_0*theta2)
    J1 = Sbar_1_0.reshape(6,1)
    J2 = mr.Adjoint(T_01) @ Sbar_2_0.reshape(6,1)
    J3 = mr.Adjoint(T_01@T_12) @ Sbar_3_0.reshape(6,1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    return  np.block([J1, J2, J3])


In [9]:
J = myGeometrixJacobian(theta1,theta2,theta3)
print(J)

[[ 0.         0.5        0.8660254]
 [ 0.        -0.8660254  0.5      ]
 [ 1.         0.         0.       ]
 [ 0.         0.         0.25     ]
 [ 0.         0.        -0.4330127]
 [ 0.        -1.         0.       ]]


In [10]:
# check whether the result agrees
J_G = plant.CalcJacobianSpatialVelocity(plant_context, JacobianWrtVariable.kQDot, G, [0,0,0], Zero_Frame, Zero_Frame)
braket_p = mr.VecToso3(T0e.translation())
E = np.block([[np.eye(3,3), 0*np.eye(3,3)],
            [-braket_p, np.eye(3,3)]])
J_A = np.linalg.inv(E)@J_G
print(J_A)


[[ 0.00000000e+00  5.00000000e-01  8.66025404e-01]
 [ 0.00000000e+00 -8.66025404e-01  5.00000000e-01]
 [ 1.00000000e+00  6.12323400e-17  3.74939946e-33]
 [ 0.00000000e+00  5.55111512e-17  2.50000000e-01]
 [ 0.00000000e+00 -5.55111512e-17 -4.33012702e-01]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00]]


In [11]:
def myAnalyticalJacobian(M_q, theta1, theta2, theta3):
    # comput q through fk
    Tbs = myPoE(M_q, theta1, theta2, theta3)
    braket_p = mr.VecToso3(Tbs[:,3])
    # construct E matrix s.t. J_a = E*J_g
    E = np.block([[np.eye(3,3), 0*np.eye(3,3)],
        [-braket_p, np.eye(3,3)]])
    # get geometry Jacobian
    J_g = myGeometrixJacobian(theta1, theta2, theta3)
    return E @ J_g
        
    

In [12]:
M_q = np.array([[0,0,-1,1+3],
[0,1,0,2],
[1,0,0,-0.5-1],
[0,0,0,1]])

Ja = myAnalyticalJacobian(M_q, theta1, theta2, theta3)
print(Ja)

[[ 0.          0.5         0.8660254 ]
 [ 0.         -0.8660254   0.5       ]
 [ 1.          0.          0.        ]
 [-3.83711731 -0.17935973  0.35355339]
 [ 2.40344144 -0.10355339 -0.61237244]
 [ 0.          3.          2.12132034]]


In [13]:
# check if it is correct
Ja_fromDrake = plant.CalcJacobianSpatialVelocity(plant_context, JacobianWrtVariable.kQDot, G, [1,2,3], Zero_Frame, Zero_Frame)
print(Ja_fromDrake)

[[ 0.00000000e+00  5.00000000e-01  8.66025404e-01]
 [ 0.00000000e+00 -8.66025404e-01  5.00000000e-01]
 [ 1.00000000e+00  6.12323400e-17  3.74939946e-33]
 [-3.83711731e+00 -1.79359734e-01  3.53553391e-01]
 [ 2.40344144e+00 -1.03553391e-01 -6.12372436e-01]
 [ 0.00000000e+00  3.00000000e+00  2.12132034e+00]]
